In [18]:
import numpy as np

In [19]:
file = open("../puzzle4.txt")
nums = [int(x) for x in file.readline().split(',')]
lines = [[int(x) for x in line.strip().split()] for index,line in enumerate(file.readlines()) if index % 6 != 0]

In [20]:
boards = []
for i in range(0, len(lines), 5):
    b = np.array(lines[i:i+5])
    boards.append(b)

In [21]:
found = False
for num in nums:
    # print("Calling number: ", num)
    for b in range(len(boards)):
        boards[b] = np.where(boards[b] == num, -1, boards[b])
        if np.isin(-5, [boards[b].sum(0), boards[b].sum(1)]):
            # print("Board", b, "won the game!")
            found = True
            break
    if found: break


        
print("Lucky board:", b)
board = np.where(boards[b] < 0, 0, boards[b])
sum = board.sum(0).sum(0).item(0)
print("The sum is:", sum)
print("The number is:", num)
print("Total score: ", sum * num)
        

Lucky board: 41
The sum is: 899
The number is: 99
Total score:  89001


In [22]:
boards

[array([[ 3, -1, 15, 54, 81],
        [56, 77, 20, -1, 25],
        [-1, 57, 67, -1, -1],
        [28, 45, -1, 84, 14],
        [91, 94, 39, -1, 85]]),
 array([[52, 60, -1, -1, -1],
        [-1, -1, 77, -1, -1],
        [ 6,  3, 75, -1, -1],
        [-1, 57, -1, 11, 91],
        [56, 84, -1, 43, 48]]),
 array([[-1, 60, 78, -1, 11],
        [79, -1, 93, 39, 63],
        [32, 31, -1, -1, 17],
        [57, 98, -1, -1,  9],
        [65, 94, 26, 77, -1]]),
 array([[-1, 68, 81, 63, 95],
        [91, 43, 98, 49, 70],
        [67, -1, -1, -1,  3],
        [65, 93, 39, 29, 34],
        [45, -1, 78, 40, 59]]),
 array([[95, 11, -1, -1, 78],
        [ 8, -1, -1, -1, -1],
        [48, 83, 93, 52, -1],
        [16, -1, -1,  1, -1],
        [-1, -1, 40, 39, 81]]),
 array([[-1, 73, 63, 93, 86],
        [-1, 76, -1, 22, 75],
        [61, -1, -1, -1, -1],
        [26, 29, 85, -1, -1],
        [-1, 78, -1, 40,  6]]),
 array([[58, -1, 95, 92, 78],
        [25, 56, 26,  9, 38],
        [43, 83, -1, -1,  8]